AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Alert Logic Cloud Defender deployment with auto-claim feature enabled.
  Includes Instance, Elastic IP, and Security Group.
Parameters:
  vpcID:
    Type: 'AWS::EC2::VPC::Id'
    Description: VPC into which Cloud Defender will be deployed. (Must have available EIPs)
  monitoringCIDR:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR netblock to be monitored. (Where agents will be installed)
  publicSubnet:
    Type: 'AWS::EC2::Subnet::Id'
    Description: >-
      ID of a DMZ subnet, with a default route to an IGW, into which Cloud
      Defender appliance will be deployed in.
  instanceType:
    Type: String
    Description: EC2 Instance Type Cloud Defender will be spun up as.
    Default: c5.xlarge
    AllowedValues:
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
Mappings:
  threatManagerAMI:
    ap-south-1:
      AMI: ami-944916fb
    eu-west-3:
      AMI: ami-2d66d050
    eu-west-2:
      AMI: ami-c66480a1
    eu-west-1:
      AMI: ami-c57336bc
    ap-northeast-2:
      AMI: ami-e768c589
    ap-northeast-1:
      AMI: ami-f07e3896
    sa-east-1:
      AMI: ami-72115a1e
    ca-central-1:
      AMI: ami-6d880f09
    ap-southeast-1:
      AMI: ami-1c1e5560
    ap-southeast-2:
      AMI: ami-3edd1b5c
    eu-central-1:
      AMI: ami-aa92ffc5
    us-east-1:
      AMI: ami-5934df24
    us-east-2:
      AMI: ami-e5fdca80
    us-west-1:
      AMI: ami-87e6ede7
    us-west-2:
      AMI: ami-5b9e1623
    us-gov-west-1:
      AMI: ami-89df5ce8
Resources:
  sgCloudDefender:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Alert Logic Cloud Defender Security Group
      VpcId: !Ref vpcID
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 204.110.218.96/27
          FromPort: '4849'
          ToPort: '4849'
        - IpProtocol: tcp
          CidrIp: 204.110.219.96/27
          FromPort: '4849'
          ToPort: '4849'
        - IpProtocol: tcp
          CidrIp: 208.71.209.32/27
          FromPort: '4849'
          ToPort: '4849'
        - IpProtocol: tcp
          CidrIp: !Ref monitoringCIDR
          FromPort: '7777'
          ToPort: '7777'
        - IpProtocol: tcp
          CidrIp: !Ref monitoringCIDR
          FromPort: '443'
          ToPort: '443'
      SecurityGroupEgress:
        - IpProtocol: tcp
          CidrIp: 204.110.218.96/27
          FromPort: '443'
          ToPort: '443'
        - IpProtocol: tcp
          CidrIp: 204.110.219.96/27
          FromPort: '443'
          ToPort: '443'
        - IpProtocol: tcp
          CidrIp: 204.110.218.96/27
          FromPort: '4138'
          ToPort: '4138'
        - IpProtocol: tcp
          CidrIp: 204.110.219.96/27
          FromPort: '4138'
          ToPort: '4138'
        - IpProtocol: tcp
          CidrIp: 208.71.209.32/27
          FromPort: '443'
          ToPort: '443'
        - IpProtocol: tcp
          CidrIp: 208.71.209.32/27
          FromPort: '4138'
          ToPort: '4138'
        - IpProtocol: udp
          CidrIp: 8.8.8.8/32
          FromPort: '53'
          ToPort: '53'
        - IpProtocol: udp
          CidrIp: 8.8.4.4/32
          FromPort: '53'
          ToPort: '53'
        - IpProtocol: tcp
          CidrIp: 8.8.8.8/32
          FromPort: '53'
          ToPort: '53'
        - IpProtocol: tcp
          CidrIp: 8.8.4.4/32
          FromPort: '53'
          ToPort: '53'
      Tags:
        - Key: Name
          Value: Alert Logic Cloud Defender Security Group
  instanceTmAppliance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap
        - threatManagerAMI
        - !Ref 'AWS::Region'
        - AMI
      InstanceType: !Ref instanceType
      NetworkInterfaces:
        - GroupSet:
            - !Ref sgCloudDefender
          AssociatePublicIpAddress: 'false'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref publicSubnet
      BlockDeviceMappings:
        - DeviceName: '/dev/sda1'
          Ebs:
            VolumeType: 'gp2'
            VolumeSize: 100
            DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: Alert Logic Cloud Defender
    DependsOn: sgCloudDefender
  tmcEIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: !Ref instanceTmAppliance
      Domain: vpc
    DependsOn: instanceTmAppliance
Outputs:
  agentSecurityGroupID:
    Value: !Ref sgCloudDefender
    Description: >-
      Copy this Security Group ID into the destination fields of the new egress
      rules for the Agents' Security Groups.
